CREATE TABLE USR(
  USER_ID NUMBER(10) PRIMARY KEY,
  EMAIL VARCHAR2(100) UNIQUE NOT NULL,
  PWD VARCHAR2(50) NOT NULL,
  FIRSTNAME VARCHAR2(50) NOT NULL,
  LASTNAME VARCHAR2(50) NOT NULL,
  ROLL NUMBER(2) NOT NULL,
  APPROVED NUMBER(1) NOT NULL
);

CREATE TABLE USER_ROLLS(
  ROLL_ID NUMBER(2) PRIMARY KEY,
  ROLL_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE REIMBURSEMENTS(
  R_ID NUMBER(10) PRIMARY KEY,
  AUTHOR NUMBER(10) NOT NULL,
  R_RESOLVER NUMBER(10),
  AMOUNT NUMBER(10,2) NOT NULL,
  SUBMIT_DATE VARCHAR2(30) NOT NULL,
  RESOLVE_DATE VARCHAR2(30),
  R_TYPE NUMBER(3) NOT NULL,
  R_DESC VARCHAR2(250),
  R_STATUS NUMBER(3) NOT NULL
);

CREATE TABLE REIMBURSEMENT_TYPE(
  R_TYPE_ID NUMBER(3) PRIMARY KEY,
  R_TYPE VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE STATUS_TYPE(
  STATUS_TYPE_ID NUMBER(10) PRIMARY KEY,
  STATUS_TYPE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RESUBMIT(
  RESUBMIT_ID NUMBER(10) PRIMARY KEY,
  ORIG_R_ID NUMBER(10),
  RE_AUTHOR NUMBER(10) NOT NULL,
  RE_RESOLVER NUMBER(10),
  RE_AMOUNT NUMBER(10,2) NOT NULL,
  RESUBMIT_DATE VARCHAR2(30) NOT NULL,
  RE_RESOLVE_DATE VARCHAR2(30),
  RE_TYPE NUMBER(3) NOT NULL,
  RE_DESC VARCHAR2(250),
  RE_STATUS NUMBER(3) NOT NULL
);


----------------------------------Set Constraints-------------------------------
--- REIMBERSEMENT CONSTRAINTS
ALTER TABLE REIMBURSEMENTS
  ADD CONSTRAINT author_to_user_id_fk
  FOREIGN KEY (AUTHOR)
  REFERENCES USR(USER_ID)
  ON DELETE CASCADE;
ALTER TABLE REIMBURSEMENTS
  ADD CONSTRAINT resolver_to_user_id_fk
  FOREIGN KEY (R_RESOLVER)
  REFERENCES USR(USER_ID)
  ON DELETE CASCADE;
ALTER TABLE REIMBURSEMENTS
  ADD CONSTRAINT status_type_fk
  FOREIGN KEY (R_STATUS)
  REFERENCES STATUS_TYPE(STATUS_TYPE_ID)
  ON DELETE CASCADE;
ALTER TABLE REIMBURSEMENTS
  ADD CONSTRAINT reimbursement_type_fk
  FOREIGN KEY (R_TYPE)
  REFERENCES REIMBURSEMENT_TYPE(R_TYPE_ID)
  ON DELETE CASCADE;
 
--- RESUBMIT CONSTRAINTS  
ALTER TABLE RESUBMIT
  ADD CONSTRAINT resubmit_to_orig_id
  FOREIGN KEY (ORIG_R_ID)
  REFERENCES REIMBURSEMENTS(R_ID)
  ON DELETE CASCADE;
ALTER TABLE RESUBMIT
  ADD CONSTRAINT REauthor_to_user_id_fk
  FOREIGN KEY (RE_AUTHOR)
  REFERENCES USR(USER_ID)
  ON DELETE CASCADE;
ALTER TABLE RESUBMIT
  ADD CONSTRAINT REresolver_to_user_id_fk
  FOREIGN KEY (RE_RESOLVER)
  REFERENCES USR(USER_ID)
  ON DELETE CASCADE;
ALTER TABLE RESUBMIT
  ADD CONSTRAINT REstatus_type_fk
  FOREIGN KEY (RE_STATUS)
  REFERENCES STATUS_TYPE(STATUS_TYPE_ID)
  ON DELETE CASCADE;
ALTER TABLE RESUBMIT
  ADD CONSTRAINT REreimbursement_type_fk
  FOREIGN KEY (RE_TYPE)
  REFERENCES REIMBURSEMENT_TYPE(R_TYPE_ID)
  ON DELETE CASCADE;
  
--- USER ROLL CONSTRAINTS
ALTER TABLE USR
  ADD CONSTRAINT roll_type_fk
  FOREIGN KEY (ROLL)
  REFERENCES USER_ROLLS(ROLL_ID)
  ON DELETE CASCADE;
  
-------------------------------Create Sequences--------------------------------
CREATE SEQUENCE USR_SEQ;
CREATE SEQUENCE REIMBURSEMENT_SEQ;
CREATE SEQUENCE RESUBMIT_SEQ;

----------------------------Create Auto-gen Triggers----------------------------
CREATE OR REPLACE TRIGGER USER_TRIG
BEFORE INSERT ON USR
FOR EACH ROW
BEGIN 
    :NEW.USER_ID := USR_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER REIMBURSEMENT_TRIG
BEFORE INSERT ON REIMBURSEMENTS
FOR EACH ROW
BEGIN 
    :NEW.R_ID := REIMBURSEMENT_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER RESUBMIT_TRIG
BEFORE INSERT ON RESUBMIT
FOR EACH ROW
BEGIN 
    :NEW.RESUBMIT_ID := RESUBMIT_SEQ.NEXTVAL;
END;
/



-----------------------------POPULATE TYPE TABLES-------------------------------
INSERT INTO USER_ROLLS (ROLL_ID, ROLL_TYPE)
  VALUES(1, 'EMPLOYEE');
INSERT INTO USER_ROLLS (ROLL_ID, ROLL_TYPE)
  VALUES(2, 'MANAGER');

INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, STATUS_TYPE)
  VALUES(1, 'PENDING');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, STATUS_TYPE)
  VALUES(2, 'APPROVED');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, STATUS_TYPE)
  VALUES(3, 'DENIED');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, STATUS_TYPE)
  VALUES(4, 'RESUBMITTED');

INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(1,'Lodging');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(2,'Travel');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(3,'Meals');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(4,'Client Hospitality');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(5,'Software');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(6,'Hardware');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(7,'Certifications');
INSERT INTO REIMBURSEMENT_TYPE(R_TYPE_ID, R_TYPE)
  VALUES(8,'Other');



-------------------------------STORED PROCEDURES--------------------------------









