/*
  DDL (Data Definition Language) script for book store (Barns & Noble) Example
*/

--CREATE TABLE [table name]([column info)]);
CREATE TABLE BN_GENRE(
  GENRE_ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(36) NOT NULL UNIQUE
  );

CREATE TABLE BN_AUTHOR(
  AUTHOR_ID NUMBER(10) PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50),
  BIO VARCHAR2(1000)
);

CREATE TABLE BN_BOOK(
  BOOK_ID NUMBER(10) PRIMARY KEY,
  ISBN VARCHAR2(10) UNIQUE NOT NULL,
  AUTHOR NUMBER(10) NOT NULL,
  TITLE VARCHAR2(256) NOT NULL,
  PRICE NUMBER(6,2) NOT NULL,                   -- NUMBER(digits, decimals)
  GENRE_ID NUMBER(10) NOT NULL,
  
  CONSTRAINT FK_BOOK_GENRE 
  FOREIGN KEY (GENRE_ID) REFERENCES BN_GENRE(GENRE_ID),
  FOREIGN KEY (AUTHOR) REFERENCES BN_AUTHOR(AUTHOR_ID)
);



  